### ISSUE TITLE
404 Error When Selecting 'Login to Google Contacts'

### ISSUE THREAD

**Issue by JeffHochberg** [splitbrain/googlephonefix#9] opened 2019-11-05 19:56 UTC
Hello,

It looks like it's been a long time since this code was maintained, so I guess there's a really good chance that it is no longer supported.

I tried launching the app from both http://splitbrain.github.io/googlephonefix/ as well as cloning the repository locally and launching the index.html directly from the local filesystem on a desktop running Ubuntu 18.04.

In both cases, when you click the button to 'Login to Google Contacts' I get redirected to a URL that returns a 404 error. Is this to be expected? I see another comment about the code using an old outdated Google API, so I guess it's possible that's what I'm running into. I just want to confirm that's the case.

Thanks!

**Comment by splitbrain** [comment] 2019-11-06 08:23
yeah. duplicate of #8

**Closed as completed by splitbrain** 2019-11-06 08:23 UTC
